name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - uses: android-actions/setup-android@v2
    - name: Set up Android SDK
      with:
        api-level: 34
        build-tools-version: 35.0.0
  
    - name: Create output directories
      run: |
        mkdir -p ./bin
        mkdir -p ./lib
  
    - name: Compile Java
      run: |
        javac -cp "$ANDROID_HOME/platforms/android-34/android.jar" \
          ./src/AudioServer.java -d ./bin
  
    - name: Convert to DEX
      run: |
        rm -f ./bin/classes.dex
        "$ANDROID_HOME/build-tools/35.0.0/d8" \
          ./bin/AudioServer.class --output ./bin
    
    - name: Create JAR
      run: |
        rm -f ./lib/AudioServer.jar
        jar cvf ./lib/AudioServer.jar -C ./bin classes.dex
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: audio-server-jar
        path: ./lib/AudioServer.jar
        retention-days: 30
